apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: upf-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: upf
  namespaceSelector:
    matchNames:
      - nfv-5g
  endpoints:
    - port: metrics
      interval: 15s
